language: node_js
node_js:
  - "0.12"
after_script: NODE_ENV=test ./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
notifications:
  slack: illumineto:ATF0Oh0hUQegHaJ5VrwyRgbd
